1. Create a class called Employee, then perform the following actions.

.Create a constructor to initialize name, family, salary, and department.

.Create a data member to count the number of employees.

• Add a function to calculate the average income.

• Create a class called Fulltime Employee, and it should inherit the Employee class's properties.

• Create instances of the Employee class and the Fulltime Employee class, then call each class's member functions.



In [1]:
class Employee:
    emp_total = 0  # Class variable to calculate the total employees


    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.emp_total += 1  #Increase the number of employees


    def avg_salary(employees):
        employee_whole_salary = sum(emp.salary for emp in employees)
        return employee_whole_salary / len(employees) if len(employees) > 0 else 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


empe1 = Employee("Ajay M", "Fam x",80000 , "Accounts and finance")
empe2 = Employee("Kartheek B", "Fam y", 59000, "product development")
empe3 = Employee("Maneesh M", "Fam z", 70000, "sales and marketing")

fulltime_emply1 = FulltimeEmployee("John P", "Family T", 90000, "IT")
fulltime_emply2 = FulltimeEmployee("azhar md", "Family H", 65000, "Infrastructures")

#Using member functions in calls

employees = [empe1, empe2, empe3]
empeey56=[fulltime_emply1, fulltime_emply2]
avg_salary_val = Employee.avg_salary(employees)
avgee12=FulltimeEmployee.avg_salary(empeey56)
print(f" employees count: {Employee.emp_total}")
print(f"Avge income of Employees: {avg_salary_val}")
print(f"Avge income of Fulltime Employees: {avgee12}")


 employees count: 5
Avge income of Employees: 69666.66666666667
Avge income of Fulltime Employees: 77500.0


2. Numpy

Create a random vector of size 20 with only float values between 1 and 20 using NumPy.

Replace the maximum in each row with 0 (axis=1), then resize the array to 4 by 5.

(You CANNOT use a for loop to implement it.)

In [5]:
import numpy as np

random_vect = np.round(np.random.uniform(1, 20, size=20), 1)
print("Real matrix=",random_vect)

reshape__matrix =  random_vect.reshape(4, 5)

max_indices = np.argmax(reshape__matrix, axis=1)
reshape__matrix[np.arange(4), max_indices] = 0
print("\n new(reshape) matrix:")
print(reshape__matrix)

Real matrix= [11.7  9.2  6.2  2.9  5.  14.7  7.5  4.9  1.4  1.8 15.1 10.4  6.2  4.2
  7.6 18.2 13.  18.4 16.2 11.3]

 new(reshape) matrix:
[[ 0.   9.2  6.2  2.9  5. ]
 [ 0.   7.5  4.9  1.4  1.8]
 [ 0.  10.4  6.2  4.2  7.6]
 [18.2 13.   0.  16.2 11.3]]
